"""init schema

Revision ID: 150d02272f8c
Revises: 
Create Date: 2025-10-01 10:19:26.221257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150d02272f8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('unix_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("ix_transactions_symbol", "transactions", ["symbol"])
    op.create_index("ix_transactions_unix_time", "transactions", ["unix_time"])
    # with op.batch_alter_table('transactions', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_transactions_symbol'), ['symbol'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_transactions_unix_time'), ['unix_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    op.drop_index("ix_transactions_unix_time", table_name="transactions")
    op.drop_index("ix_transactions_symbol", table_name="transactions")
    op.drop_table("transactions")
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('transactions', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_transactions_unix_time'))
    #     batch_op.drop_index(batch_op.f('ix_transactions_symbol'))

    # op.drop_table('transactions')
    # ### end Alembic commands ###
